language: php

matrix:
  allow_failures:
    - env: LARAVEL=dev-master
    - php: 7.3
  include:
    -
      env: LARAVEL=5.3
      php: 7.1
    -
      env: LARAVEL=5.4
      php: 7.1
    -
      env: LARAVEL=5.6
      php: 7.2
    -
      env: LARAVEL=5.7
      php: 7.2
    -
      env: LARAVEL=dev-master
      php: 7.2
    -
      env: LARAVEL=dev-master
      php: 7.3

sudo: false

git:
  depth: 3

services:
  - mysql

before_install:
  - mysql -v -e 'CREATE DATABASE IF NOT EXISTS laravel;'

install:
  - composer install

  # Install laravel project in a separate directory for functional tests.
  - TESTDIR=$(pwd)
  - cd ..
  - composer create-project laravel/laravel=$LARAVEL laravel --prefer-dist --no-dev
  - cd laravel
  - LARAVELDIR=$(pwd)

  # Configure laravel env to use travis credentials.
  - sed -i 's#^DB_USERNAME=[a-z]*$#DB_USERNAME=travis#' .env
  - sed -i 's#^DB_PASSWORD=[a-z]*$#DB_PASSWORD=#' .env
  - sed -i 's#^DB_DATABASE=[a-z]*$#DB_DATABASE=laravel#' .env

  # Create the migrations table at least.
  - ./artisan migrate:install

  - cd $TESTDIR

script:
  - vendor/bin/phpunit --group larama,larama_functional,larama_db --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - head $TRAVIS_BUILD_DIR/coverage.txt
