language: php

php:
  - 5.6
  - 7.0
env:
  - LARAVEL=5.3
  - LARAVEL=5.4

sudo: false

git:
  depth: 3

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS homestead'

install:
  - composer install

  # Install laravel project in a separate directory for functional tests.
  - TESTDIR=$(pwd)
  - cd ..
  - composer create-project laravel/laravel=$LARAVEL laravel --prefer-dist
  - cd laravel
  - LARAVELDIR=$(pwd)

  # Configure laravel env to use travis credentials.
  - sed -i 's#DB_USERNAME=homestead#DB_USERNAME=travis#' .env
  - sed -i 's#DB_PASSWORD=secret#DB_PASSWORD=#' .env

  # Create the migrations table at least.
  - ./artisan migrate:install

after_install:
  - cd $TESTDIR

script:
  - vendor/bin/phpunit --group larama,larama_functional,larama_db --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - head $TRAVIS_BUILD_DIR/coverage.txt