language: php

php:
  - 5.6
  - 7.0
env:
  - LARAVEL=5.3
  - LARAVEL=5.4

sudo: false

git:
  depth: 3

install:
  - composer install

  # Install laravel project in a separate directory for functional tests.
  - TESTDIR=$(pwd)
  - cd ..
  - composer create-project laravel/laravel=$LARAVEL laravel --prefer-dist
  - LARAVELDIR=$(pwd)
  - cd $TESTDIR

script:
  - vendor/bin/phpunit --group larama,larama_functional --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - head $TRAVIS_BUILD_DIR/coverage.txt