language: php

php:
  - 5.6
  - 7.0

sudo: false

git:
  depth: 3

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - head $TRAVIS_BUILD_DIR/coverage.txt