#!/usr/bin/env php
<?php

/**
 * @file
 * Laraman application.
 */

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require __DIR__  . '/../vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../../autoload.php')) {
    require __DIR__ . '/../../../autoload.php';
}

use Radcliffe\Laraman\Console\Laraman;

$app = new Laraman('laraman (Laravel Manager)', '0.1');

$app->run();
