#!/usr/bin/env php
<?php

/**
 * @file
 * Larama application.
 */

if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    $loader = require_once __DIR__  . '/../vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../../autoload.php')) {
    $loader = require_once __DIR__ . '/../../../autoload.php';
}

use Radcliffe\Larama\Console\Larama;

$app = new Larama('larama (Laravel Manager)', '0.2');

$app->run();
